"""WHO-style radiology pattern knowledge base for image explanation grounding."""

RADIOLOGY_KNOWLEDGE_BASE = [
    {
        "id": "thorax_001",
        "category": "thoracic",
        "modality": ["xray", "ct"],
        "pattern": "Consolidation",
        "description": "Region of lung opacification where air is replaced by fluid or tissue. Air bronchograms may be seen in lobar pneumonia.",
        "associated_conditions": ["Pneumonia", "Lobar pneumonia", "COVID-19", "Pulmonary edema"],
        "body_region": "lung",
        "urgency": "high",
        "keywords": ["consolidation", "opacification", "air bronchogram", "lobar", "pneumonia"],
    },
    {
        "id": "thorax_002",
        "category": "thoracic",
        "modality": ["xray"],
        "pattern": "Collapse / Atelectasis",
        "description": "Airless lung segment caused by obstruction or compression, usually producing radiographic volume loss.",
        "associated_conditions": ["Atelectasis", "Bronchial obstruction", "Pleural effusion"],
        "body_region": "lung",
        "urgency": "medium",
        "keywords": ["atelectasis", "collapse", "volume loss", "airless", "obstruction"],
    },
    {
        "id": "thorax_003",
        "category": "thoracic",
        "modality": ["xray", "ultrasound"],
        "pattern": "Pleural Effusion",
        "description": "Fluid in the pleural cavity, often visible as costophrenic angle blunting on chest radiograph.",
        "associated_conditions": ["Bacterial pneumonia", "Tuberculosis", "Heart failure", "Malignancy"],
        "body_region": "pleura",
        "urgency": "medium",
        "keywords": ["effusion", "pleural", "fluid", "costophrenic", "blunting"],
    },
    {
        "id": "thorax_004",
        "category": "thoracic",
        "modality": ["xray", "ct"],
        "pattern": "Pulmonary Cavity",
        "description": "Gas-filled space within pulmonary consolidation, associated with necrotizing infection, abscess, or tuberculosis.",
        "associated_conditions": ["Tuberculosis", "Necrotizing pneumonia", "Lung abscess", "Fungal infection"],
        "body_region": "lung",
        "urgency": "high",
        "keywords": ["cavity", "cavitation", "gas-filled", "tuberculosis", "abscess", "necrotizing"],
    },
    {
        "id": "thorax_005",
        "category": "thoracic",
        "modality": ["xray", "ct"],
        "pattern": "Ground-Glass Opacity",
        "description": "Hazy increased opacity without obscuring underlying vessels, commonly described in viral pneumonia and edema patterns.",
        "associated_conditions": ["COVID-19", "Viral pneumonia", "Pulmonary fibrosis", "Pulmonary edema"],
        "body_region": "lung",
        "urgency": "high",
        "keywords": ["ground-glass", "opacity", "GGO", "COVID", "viral pneumonia", "peripheral"],
    },
    {
        "id": "thorax_006",
        "category": "thoracic",
        "modality": ["xray"],
        "pattern": "Bronchial Wall Thickening + Hyperinflation",
        "description": "Thickened bronchial walls with increased lung volumes suggesting air trapping.",
        "associated_conditions": ["Asthma", "Chronic bronchitis", "COPD"],
        "body_region": "lung",
        "urgency": "low",
        "keywords": ["bronchial wall thickening", "hyperinflation", "air trapping", "asthma", "COPD"],
    },
    {
        "id": "thorax_007",
        "category": "thoracic",
        "modality": ["xray"],
        "pattern": "Pulmonary Hypertranslucency + Flattened Diaphragm",
        "description": "Increased radiolucency with flattened diaphragms, often reflecting emphysema or chronic obstructive change.",
        "associated_conditions": ["Emphysema", "COPD"],
        "body_region": "lung",
        "urgency": "low",
        "keywords": ["hypertranslucency", "flattened diaphragm", "emphysema", "COPD", "barrel chest"],
    },
    {
        "id": "thorax_008",
        "category": "thoracic",
        "modality": ["xray", "ct"],
        "pattern": "Tram-Track Lines / Dilated Bronchi",
        "description": "Dilated bronchi appearing as parallel tram-track lines, supporting chronic airway damage.",
        "associated_conditions": ["Bronchiectasis", "Cystic fibrosis", "Chronic infection"],
        "body_region": "lung",
        "urgency": "medium",
        "keywords": ["tram-track", "dilated bronchi", "bronchiectasis", "cystic fibrosis"],
    },
    {
        "id": "thorax_009",
        "category": "thoracic",
        "modality": ["ct"],
        "pattern": "Reticular Opacities + Honeycombing",
        "description": "Fine reticular pattern with honeycombing, typical of fibrotic interstitial lung disease patterns.",
        "associated_conditions": ["Pulmonary fibrosis", "IPF", "Interstitial lung disease", "Connective tissue disease"],
        "body_region": "lung",
        "urgency": "medium",
        "keywords": ["reticular", "honeycombing", "fibrosis", "interstitial", "UIP pattern"],
    },
    {
        "id": "thorax_010",
        "category": "thoracic",
        "modality": ["xray"],
        "pattern": "Nodular Opacities + Pleural Plaques",
        "description": "Nodular shadows with pleural plaques, raising occupational dust exposure disease patterns.",
        "associated_conditions": ["Pneumoconiosis", "Silicosis", "Asbestosis", "Coal workers pneumoconiosis"],
        "body_region": "lung",
        "urgency": "medium",
        "keywords": ["nodular", "pleural plaques", "pneumoconiosis", "silicosis", "asbestosis", "occupational"],
    },
    {
        "id": "thorax_011",
        "category": "thoracic",
        "modality": ["xray", "ct"],
        "pattern": "Pleural Line Without Peripheral Lung Markings",
        "description": "Visible pleural edge with absent distal lung markings, concerning for pneumothorax.",
        "associated_conditions": ["Pneumothorax", "Tension pneumothorax", "Trauma"],
        "body_region": "pleura",
        "urgency": "critical",
        "keywords": ["pneumothorax", "pleural line", "absent lung markings", "collapsed lung"],
    },
    {
        "id": "thorax_012",
        "category": "thoracic",
        "modality": ["xray"],
        "pattern": "Enlarged Cardiac Silhouette",
        "description": "Increased cardiothoracic ratio suggesting cardiomegaly or pericardial effusion depending on context.",
        "associated_conditions": ["Cardiomegaly", "Heart failure", "Pericardial effusion"],
        "body_region": "heart",
        "urgency": "medium",
        "keywords": ["cardiomegaly", "cardiac silhouette", "CTR", "heart failure"],
    },
    {
        "id": "thorax_013",
        "category": "thoracic",
        "modality": ["xray", "ct"],
        "pattern": "Mediastinal Widening",
        "description": "Widened mediastinum requiring correlation for vascular injury, mass, lymphadenopathy, or technical factors.",
        "associated_conditions": ["Aortic injury", "Mediastinal mass", "Lymphadenopathy"],
        "body_region": "mediastinum",
        "urgency": "high",
        "keywords": ["mediastinal widening", "aorta", "mass", "lymphadenopathy"],
    },
    {
        "id": "msk_001",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Sunburst Periosteal Reaction",
        "description": "Aggressive spiculated periosteal reaction, classically associated with osteogenic sarcoma.",
        "associated_conditions": ["Osteogenic sarcoma", "Osteosarcoma", "Aggressive bone tumor"],
        "body_region": "bone",
        "urgency": "critical",
        "keywords": ["sunburst", "periosteal reaction", "osteosarcoma", "spiculated", "aggressive"],
    },
    {
        "id": "msk_002",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Punched-Out Lytic Lesions",
        "description": "Multiple well-defined lytic lesions, especially in skull, spine, or pelvis, compatible with myeloma pattern.",
        "associated_conditions": ["Multiple myeloma", "Bone metastases"],
        "body_region": "bone",
        "urgency": "critical",
        "keywords": ["punched-out", "lytic lesions", "multiple myeloma", "skull", "pelvis", "spine"],
    },
    {
        "id": "msk_003",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Onion-Skin Periosteal Reaction",
        "description": "Laminated periosteal reaction, associated with Ewing sarcoma and sometimes osteomyelitis.",
        "associated_conditions": ["Ewing sarcoma", "Osteomyelitis"],
        "body_region": "bone",
        "urgency": "critical",
        "keywords": ["onion skin", "periosteal", "Ewing sarcoma", "diaphysis", "laminated"],
    },
    {
        "id": "msk_004",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Expansive Subarticular Lytic Lesion",
        "description": "Expansile subarticular lytic lesion, characteristic of giant cell tumor pattern.",
        "associated_conditions": ["Giant cell tumor", "GCT"],
        "body_region": "bone",
        "urgency": "medium",
        "keywords": ["subarticular", "expansive", "lytic", "giant cell tumor", "locally aggressive"],
    },
    {
        "id": "msk_005",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Callus Formation / Fracture Union",
        "description": "Bone healing response; absent or poor callus may suggest delayed union or non-union.",
        "associated_conditions": ["Fracture healing", "Non-union", "Mal-union"],
        "body_region": "bone",
        "urgency": "low",
        "keywords": ["callus", "fracture union", "healing", "non-union", "periosteal reaction"],
    },
    {
        "id": "msk_006",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Decreased Bone Density / Osteopenia",
        "description": "Generalized bone density reduction, suggesting osteopenia or osteoporosis; DEXA is definitive.",
        "associated_conditions": ["Osteoporosis", "Osteopenia", "Metabolic bone disease"],
        "body_region": "bone",
        "urgency": "low",
        "keywords": ["osteopenia", "osteoporosis", "bone density", "trabecular", "cortical thinning"],
    },
    {
        "id": "msk_007",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Inferior Rib Notching",
        "description": "Inferior rib margin notching from enlarged intercostal arteries, classically seen in collateral circulation.",
        "associated_conditions": ["Coarctation of aorta", "Collateral circulation"],
        "body_region": "rib",
        "urgency": "high",
        "keywords": ["rib notching", "inferior", "coarctation", "aorta", "collateral"],
    },
    {
        "id": "msk_008",
        "category": "musculoskeletal",
        "modality": ["xray"],
        "pattern": "Lytic Rib Destruction",
        "description": "Destructive lytic rib lesion, often metastatic or invasive tumor pattern.",
        "associated_conditions": ["Rib metastases", "Breast cancer", "Lung cancer", "Pancoast tumor"],
        "body_region": "rib",
        "urgency": "critical",
        "keywords": ["lytic", "rib destruction", "metastases", "Pancoast", "carcinoma"],
    },
    {
        "id": "msk_009",
        "category": "musculoskeletal",
        "modality": ["xray", "ct"],
        "pattern": "Acute Fracture Line with Displacement",
        "description": "Cortical break with displacement or angulation requiring stability and neurovascular assessment.",
        "associated_conditions": ["Acute fracture", "Trauma", "Pathologic fracture"],
        "body_region": "bone",
        "urgency": "high",
        "keywords": ["fracture", "displacement", "cortical break", "trauma", "angulation"],
    },
    {
        "id": "spine_001",
        "category": "spinal",
        "modality": ["xray", "ct", "mri"],
        "pattern": "Bamboo Spine",
        "description": "Fusion of vertebral bodies with syndesmophytes, supporting ankylosing spondylitis pattern.",
        "associated_conditions": ["Ankylosing spondylitis", "Sacroiliitis", "Spondyloarthropathy"],
        "body_region": "spine",
        "urgency": "medium",
        "keywords": ["bamboo spine", "syndesmophytes", "ankylosing spondylitis", "sacroiliitis", "fusion"],
    },
    {
        "id": "spine_002",
        "category": "spinal",
        "modality": ["xray"],
        "pattern": "Vertebral Fracture / Dislocation",
        "description": "Vertebral fracture or dislocation; assess stability and risk of cord injury.",
        "associated_conditions": ["Spinal trauma", "Spinal cord injury", "Road traffic accident"],
        "body_region": "spine",
        "urgency": "critical",
        "keywords": ["vertebral fracture", "dislocation", "spinal trauma", "cord injury", "instability"],
    },
    {
        "id": "abdo_001",
        "category": "abdominal",
        "modality": ["xray"],
        "pattern": "Free Intraperitoneal Air (Pneumoperitoneum)",
        "description": "Free subdiaphragmatic air on upright film, an emergency sign of hollow viscus perforation.",
        "associated_conditions": ["Bowel perforation", "Perforated peptic ulcer", "Perforated appendix"],
        "body_region": "abdomen",
        "urgency": "critical",
        "keywords": ["pneumoperitoneum", "free air", "subdiaphragmatic", "perforation", "emergency"],
    },
    {
        "id": "abdo_002",
        "category": "abdominal",
        "modality": ["xray"],
        "pattern": "Dilated Bowel Loops with Air-Fluid Levels",
        "description": "Distended bowel with air-fluid levels on upright film, supporting intestinal obstruction.",
        "associated_conditions": ["Intestinal obstruction", "Ileus", "Volvulus"],
        "body_region": "abdomen",
        "urgency": "critical",
        "keywords": ["dilated bowel", "air-fluid levels", "obstruction", "ileus", "volvulus"],
    },
    {
        "id": "abdo_003",
        "category": "abdominal",
        "modality": ["xray", "ultrasound"],
        "pattern": "Opaque Calcification in RUQ",
        "description": "Right upper quadrant calcification may indicate gallstones; ultrasound is preferred for cholelithiasis.",
        "associated_conditions": ["Cholelithiasis", "Gallstones", "Cholecystitis"],
        "body_region": "abdomen",
        "urgency": "medium",
        "keywords": ["gallstones", "calcification", "RUQ", "cholelithiasis", "cholecystitis"],
    },
    {
        "id": "neuro_001",
        "category": "neurological",
        "modality": ["ct", "mri"],
        "pattern": "Intracranial Space-Occupying Lesion",
        "description": "Mass lesion causing mass effect, midline shift, or herniation risk.",
        "associated_conditions": ["Brain tumor", "Cerebral abscess", "Subdural hematoma", "Metastasis"],
        "body_region": "brain",
        "urgency": "critical",
        "keywords": ["space-occupying", "SOL", "midline shift", "herniation", "mass lesion", "R90"],
    },
    {
        "id": "neuro_002",
        "category": "neurological",
        "modality": ["ct"],
        "pattern": "Hyperdense Area on CT (Hemorrhagic Stroke)",
        "description": "Hyperdense non-contrast CT focus compatible with acute hemorrhage pattern.",
        "associated_conditions": ["Hemorrhagic stroke", "Intracerebral hemorrhage", "Subarachnoid hemorrhage"],
        "body_region": "brain",
        "urgency": "critical",
        "keywords": ["hyperdense", "hemorrhage", "stroke", "ICH", "subarachnoid", "thrombolysis"],
    },
    {
        "id": "breast_001",
        "category": "breast",
        "modality": ["mammography"],
        "pattern": "Microcalcifications",
        "description": "Tiny calcium deposits; clustered microcalcifications may signal early malignancy and need mammographic correlation.",
        "associated_conditions": ["Breast carcinoma", "DCIS", "Fibrocystic changes"],
        "body_region": "breast",
        "urgency": "high",
        "keywords": ["microcalcifications", "mammography", "breast cancer", "DCIS", "malignancy", "clustered"],
    },
]


CHEXNET_LABELS_EXTENDED = {
    "Atelectasis": {"icd10": "J98.1", "urgency": "medium", "body_region": "lung"},
    "Cardiomegaly": {"icd10": "I51.7", "urgency": "medium", "body_region": "heart"},
    "Effusion": {"icd10": "J90", "urgency": "medium", "body_region": "pleura"},
    "Infiltration": {"icd10": "J18.9", "urgency": "high", "body_region": "lung"},
    "Mass": {"icd10": "R91.8", "urgency": "high", "body_region": "lung"},
    "Nodule": {"icd10": "R91.1", "urgency": "medium", "body_region": "lung"},
    "Pneumonia": {"icd10": "J18.9", "urgency": "high", "body_region": "lung"},
    "Pneumothorax": {"icd10": "J93.9", "urgency": "critical", "body_region": "pleura"},
    "Consolidation": {"icd10": "J18.1", "urgency": "high", "body_region": "lung"},
    "Edema": {"icd10": "J81", "urgency": "high", "body_region": "lung"},
    "Emphysema": {"icd10": "J43.9", "urgency": "medium", "body_region": "lung"},
    "Fibrosis": {"icd10": "J84.1", "urgency": "medium", "body_region": "lung"},
    "Pleural_Thickening": {"icd10": "J92.9", "urgency": "low", "body_region": "pleura"},
    "Hernia": {"icd10": "K44.9", "urgency": "medium", "body_region": "diaphragm"},
    "Tuberculosis": {"icd10": "A15.3", "urgency": "high", "body_region": "lung"},
    "COVID-19_Pneumonia": {"icd10": "U07.1", "urgency": "high", "body_region": "lung"},
    "Bronchiectasis": {"icd10": "J47", "urgency": "medium", "body_region": "lung"},
    "Pneumoconiosis": {"icd10": "J64", "urgency": "medium", "body_region": "lung"},
    "Cavity": {"icd10": "J98.4", "urgency": "high", "body_region": "lung"},
    "Ground_Glass_Opacity": {"icd10": "R91.8", "urgency": "high", "body_region": "lung"},
    "Osteosarcoma": {"icd10": "C40.9", "urgency": "critical", "body_region": "bone"},
    "Multiple_Myeloma_Lesions": {"icd10": "C90.0", "urgency": "critical", "body_region": "bone"},
    "Vertebral_Fracture": {"icd10": "S32.009", "urgency": "critical", "body_region": "spine"},
    "Bowel_Obstruction": {"icd10": "K56.6", "urgency": "critical", "body_region": "abdomen"},
    "Pneumoperitoneum": {"icd10": "K66.0", "urgency": "critical", "body_region": "abdomen"},
    "Fracture": {"icd10": "T14.2", "urgency": "high", "body_region": "bone"},
    "Mediastinal_Widening": {"icd10": "R93.8", "urgency": "high", "body_region": "mediastinum"},
    "No Finding": {"icd10": "Z03.89", "urgency": "none", "body_region": "none"},
    "No_Finding": {"icd10": "Z03.89", "urgency": "none", "body_region": "none"},
}


REPORT_TEMPLATES = {
    "thoracic": {
        "sections": ["Lung Fields", "Pleura", "Cardiac Silhouette", "Mediastinum", "Bony Thorax", "Diaphragm"],
        "standard_observations": [
            "Lung volumes",
            "Parenchymal opacities",
            "Pleural effusion",
            "Cardiomegaly",
            "Mediastinal widening",
            "Rib abnormalities",
        ],
        "urgency_flags": ["Pneumothorax", "Pneumoperitoneum", "Tension pneumothorax", "Massive effusion"],
    },
    "musculoskeletal": {
        "sections": ["Cortical Integrity", "Medullary Cavity", "Periosteal Reaction", "Soft Tissue", "Joint Space", "Bone Density"],
        "standard_observations": [
            "Fracture line",
            "Displacement",
            "Periosteal reaction type",
            "Lytic vs sclerotic lesion",
            "Joint space narrowing",
        ],
        "urgency_flags": ["Osteosarcoma pattern", "Multiple myeloma lesions", "Pathological fracture"],
    },
    "abdominal": {
        "sections": ["Bowel Gas Pattern", "Solid Organs", "Calcifications", "Free Air", "Soft Tissue Masses"],
        "standard_observations": ["Bowel dilatation", "Air-fluid levels", "Pneumoperitoneum", "Organomegaly", "Calculi"],
        "urgency_flags": ["Pneumoperitoneum", "Bowel obstruction", "Volvulus"],
    },
    "neurological": {
        "sections": ["Parenchyma", "Ventricles", "Midline", "Skull Vault", "Extra-axial Spaces"],
        "standard_observations": ["Midline shift", "Space-occupying lesion", "Hemorrhage", "Edema", "Skull fracture"],
        "urgency_flags": ["Midline shift", "Hemorrhagic stroke", "Herniation", "Acute hydrocephalus"],
    },
    "spinal": {
        "sections": ["Vertebral Alignment", "Vertebral Bodies", "Disc Spaces", "Posterior Elements", "Soft Tissues"],
        "standard_observations": [
            "Fracture or dislocation",
            "Vertebral height loss",
            "Disc space narrowing",
            "Syndesmophytes",
            "Spinal canal",
        ],
        "urgency_flags": ["Fracture dislocation", "Cord compression", "Unstable fracture"],
    },
}


REGION_TEMPLATE_MAP = {
    "lung": "thoracic",
    "pleura": "thoracic",
    "heart": "thoracic",
    "mediastinum": "thoracic",
    "diaphragm": "thoracic",
    "bone": "musculoskeletal",
    "rib": "musculoskeletal",
    "joint": "musculoskeletal",
    "abdomen": "abdominal",
    "bowel": "abdominal",
    "brain": "neurological",
    "skull": "neurological",
    "spine": "spinal",
}


if __name__ == "__main__":
    import json

    print(f"Knowledge base entries : {len(RADIOLOGY_KNOWLEDGE_BASE)}")
    print(f"Disease labels         : {len(CHEXNET_LABELS_EXTENDED)}")
    print(f"Report templates       : {len(REPORT_TEMPLATES)}")
    print(f"Categories             : {sorted({entry['category'] for entry in RADIOLOGY_KNOWLEDGE_BASE})}")
    print(json.dumps(RADIOLOGY_KNOWLEDGE_BASE[0], indent=2))
