"""Urinalysis pattern knowledge base for report NER/RAG grounding."""

URINALYSIS_KNOWLEDGE_BASE = [
    {
        "id": "urine_001",
        "category": "infection",
        "modality": ["urinalysis", "dipstick", "microscopy"],
        "pattern": "UTI Rule-In Pattern",
        "description": "Concurrent positive nitrite and positive leukocyte esterase supports urinary tract infection.",
        "associated_conditions": ["Urinary tract infection", "Cystitis", "Pyelonephritis"],
        "diagnostic_criteria": "Nitrite positive + leukocyte esterase positive",
        "threshold": "Culture confirmation often uses >10^5 CFU/mL",
        "urgency": "high",
        "icd10": "N39.0",
        "keywords": ["nitrite", "leukocyte esterase", "UTI", "pyuria", "WBC", "bacteria"],
    },
    {
        "id": "urine_002",
        "category": "infection",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "UTI Rule-Out Pattern",
        "description": "Negative nitrite and negative leukocyte esterase lowers likelihood of UTI in low-risk patients.",
        "associated_conditions": ["No UTI"],
        "diagnostic_criteria": "Nitrite negative + leukocyte esterase negative",
        "threshold": "High negative predictive value in low-risk presentations",
        "urgency": "none",
        "icd10": "Z03.89",
        "keywords": ["nitrite negative", "leukocyte esterase negative", "rule out UTI"],
    },
    {
        "id": "urine_003",
        "category": "infection",
        "modality": ["urinalysis", "microscopy"],
        "pattern": "Sterile Pyuria",
        "description": "Pyuria without routine bacterial growth can suggest renal tuberculosis or nonbacterial inflammation.",
        "associated_conditions": ["Renal tuberculosis", "Urogenital tuberculosis", "Interstitial nephritis"],
        "diagnostic_criteria": ">5 WBC/HPF with negative standard bacterial culture",
        "threshold": "PCR, AFB stain, or targeted culture may be needed",
        "urgency": "high",
        "icd10": "A18.11",
        "keywords": ["sterile pyuria", "renal TB", "tuberculosis", "WBC", "negative culture"],
    },
    {
        "id": "urine_004",
        "category": "infection",
        "modality": ["urinalysis", "microscopy"],
        "pattern": "Urogenital Schistosomiasis",
        "description": "Hematuria with schistosoma eggs in urine supports urogenital schistosomiasis.",
        "associated_conditions": ["Schistosomiasis", "Schistosoma haematobium", "Hematuria"],
        "diagnostic_criteria": "Eggs detected in urine sediment",
        "threshold": "Any egg detection confirms infection in the right context",
        "urgency": "high",
        "icd10": "B65.0",
        "keywords": ["schistosomiasis", "hematuria", "eggs", "schistosoma", "endemic"],
    },
    {
        "id": "urine_005",
        "category": "metabolic",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "Glucosuria",
        "description": "Urine glucose suggests hyperglycemia or renal glycosuria and should be correlated with blood glucose.",
        "associated_conditions": ["Diabetes mellitus", "Hyperglycemia", "Renal glycosuria"],
        "diagnostic_criteria": "Urine glucose positive or >=50 mg/dL",
        "threshold": "Confirm with plasma glucose or HbA1c",
        "urgency": "medium",
        "icd10": "R81",
        "keywords": ["glucosuria", "diabetes", "glucose", "dipstick", "hyperglycemia"],
    },
    {
        "id": "urine_006",
        "category": "metabolic",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "DKA Pattern",
        "description": "Glucosuria with moderate or large ketonuria can support diabetic ketoacidosis screening.",
        "associated_conditions": ["Diabetic ketoacidosis", "Type 1 diabetes", "Diabetes mellitus"],
        "diagnostic_criteria": "Glucose positive + ketones >=2+",
        "threshold": "Requires serum ketones, bicarbonate, anion gap, and clinical assessment",
        "urgency": "critical",
        "icd10": "E10.10",
        "keywords": ["DKA", "ketones", "ketonuria", "glucosuria", "acidosis"],
    },
    {
        "id": "urine_007",
        "category": "metabolic",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "HHS Pattern",
        "description": "Marked glucosuria without significant ketonuria can occur in hyperosmolar hyperglycemic state.",
        "associated_conditions": ["Hyperosmolar hyperglycemic state", "Type 2 diabetes"],
        "diagnostic_criteria": "Glucose positive + ketones negative or trace",
        "threshold": "Confirm with serum glucose/osmolality and clinical status",
        "urgency": "critical",
        "icd10": "E11.00",
        "keywords": ["HHS", "hyperosmolar", "glucosuria", "no ketones"],
    },
    {
        "id": "urine_008",
        "category": "renal",
        "modality": ["urinalysis", "dipstick", "microscopy"],
        "pattern": "Nephrotic Syndrome Pattern",
        "description": "Heavy proteinuria with lipiduria or fatty casts supports nephrotic syndrome pattern.",
        "associated_conditions": ["Nephrotic syndrome", "Glomerular disease"],
        "diagnostic_criteria": "Protein 3+ to 4+ or nephrotic-range proteinuria",
        "threshold": ">3.5 g/day proteinuria is nephrotic range",
        "urgency": "high",
        "icd10": "N04",
        "keywords": ["nephrotic", "proteinuria", "fatty casts", "oval fat body", "edema"],
    },
    {
        "id": "urine_009",
        "category": "renal",
        "modality": ["urinalysis", "microscopy"],
        "pattern": "Nephritic Syndrome - RBC Casts",
        "description": "RBC casts with hematuria support glomerular bleeding and nephritic syndrome pattern.",
        "associated_conditions": ["Nephritic syndrome", "Glomerulonephritis", "IgA nephropathy", "Lupus nephritis"],
        "diagnostic_criteria": "RBC casts present + blood positive",
        "threshold": "RBC casts are highly concerning for glomerular disease",
        "urgency": "high",
        "icd10": "N05",
        "keywords": ["RBC casts", "hematuria", "nephritic", "glomerulonephritis"],
    },
    {
        "id": "urine_010",
        "category": "renal",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "Pre-eclampsia Proteinuria",
        "description": "Proteinuria after 20 weeks gestation with hypertension supports pre-eclampsia evaluation.",
        "associated_conditions": ["Pre-eclampsia", "Eclampsia", "HELLP syndrome"],
        "diagnostic_criteria": "Protein >=1+ with pregnancy/hypertension context",
        "threshold": ">=0.3 g/24h or protein/creatinine ratio elevation",
        "urgency": "critical",
        "icd10": "O14",
        "keywords": ["pre-eclampsia", "proteinuria", "pregnancy", "hypertension"],
    },
    {
        "id": "urine_011",
        "category": "renal",
        "modality": ["urinalysis", "quantitative"],
        "pattern": "Microalbuminuria",
        "description": "Albumin-creatinine ratio elevation can be an early marker of diabetic kidney disease.",
        "associated_conditions": ["Diabetic nephropathy", "Chronic kidney disease", "Albuminuria"],
        "diagnostic_criteria": "Albumin/creatinine ratio 30-300 mg/g",
        "threshold": ">=30 mg/g is abnormal",
        "urgency": "medium",
        "icd10": "R80",
        "keywords": ["microalbuminuria", "albuminuria", "diabetic nephropathy", "ACR"],
    },
    {
        "id": "urine_012",
        "category": "hepatic",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "Conjugated Hyperbilirubinemia",
        "description": "Positive urine bilirubin suggests conjugated bilirubin from hepatocellular or biliary disease.",
        "associated_conditions": ["Hepatitis", "Biliary obstruction", "Jaundice"],
        "diagnostic_criteria": "Urine bilirubin positive",
        "threshold": "Any bilirubin is abnormal",
        "urgency": "medium",
        "icd10": "R82.2",
        "keywords": ["bilirubinuria", "bilirubin", "jaundice", "liver", "biliary"],
    },
    {
        "id": "urine_013",
        "category": "hepatic",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "Hemolytic Jaundice Pattern",
        "description": "Elevated urobilinogen with negative bilirubin can support hemolysis pattern.",
        "associated_conditions": ["Hemolytic anemia", "Sickle cell disease", "G6PD deficiency"],
        "diagnostic_criteria": "Urobilinogen elevated + bilirubin negative",
        "threshold": "Urobilinogen >1 EU/dL is elevated",
        "urgency": "medium",
        "icd10": "D59.9",
        "keywords": ["urobilinogen", "hemolytic", "anemia", "bilirubin negative"],
    },
    {
        "id": "urine_014",
        "category": "hepatic",
        "modality": ["urinalysis", "dipstick"],
        "pattern": "Obstructive Jaundice Pattern",
        "description": "Positive bilirubin with absent urobilinogen supports biliary obstruction pattern.",
        "associated_conditions": ["Bile duct obstruction", "Gallstones", "Cholestasis"],
        "diagnostic_criteria": "Bilirubin positive + urobilinogen absent",
        "threshold": "Requires liver enzymes/imaging correlation",
        "urgency": "high",
        "icd10": "K83.1",
        "keywords": ["obstructive jaundice", "bilirubin positive", "urobilinogen absent"],
    },
    {
        "id": "urine_015",
        "category": "oncology",
        "modality": ["urinalysis", "microscopy"],
        "pattern": "Bladder Cancer Hematuria",
        "description": "Painless hematuria in older adults is a warning sign for urothelial malignancy.",
        "associated_conditions": ["Bladder cancer", "Urothelial carcinoma"],
        "diagnostic_criteria": "Painless hematuria, especially persistent or recurrent",
        "threshold": "Any unexplained painless hematuria requires evaluation",
        "urgency": "high",
        "icd10": "R31",
        "keywords": ["bladder cancer", "hematuria", "painless", "urothelial"],
    },
    {
        "id": "urine_016",
        "category": "toxicology",
        "modality": ["urinalysis"],
        "pattern": "Cadmium Nephrotoxicity",
        "description": "Elevated urinary cadmium can indicate occupational exposure and tubular injury risk.",
        "associated_conditions": ["Cadmium toxicity", "Occupational nephropathy", "Tubular dysfunction"],
        "diagnostic_criteria": "Urine cadmium elevation with exposure history",
        "threshold": ">2 ug/L can indicate excessive exposure in some protocols",
        "urgency": "medium",
        "icd10": "T56.3",
        "keywords": ["cadmium", "nephrotoxicity", "occupational", "tubular"],
    },
    {
        "id": "urine_017",
        "category": "physical",
        "modality": ["urinalysis", "microscopy"],
        "pattern": "Lipiduria",
        "description": "Oval fat bodies or Maltese cross droplets with proteinuria support nephrotic syndrome pattern.",
        "associated_conditions": ["Nephrotic syndrome", "Hyperlipidemia"],
        "diagnostic_criteria": "Fat droplets or oval fat bodies on microscopy",
        "threshold": "Any lipiduria is abnormal",
        "urgency": "high",
        "icd10": "R82.9",
        "keywords": ["lipiduria", "Maltese cross", "oval fat body", "nephrotic"],
    },
    {
        "id": "urine_018",
        "category": "physical",
        "modality": ["urinalysis"],
        "pattern": "Specific Gravity Abnormality",
        "description": "Specific gravity reflects urine concentration and hydration or renal concentrating ability.",
        "associated_conditions": ["Dehydration", "Diabetes insipidus", "SIADH", "Renal tubular dysfunction"],
        "diagnostic_criteria": "Normal commonly about 1.005-1.030",
        "threshold": "<1.005 dilute; >1.030 concentrated; fixed 1.010 suggests isosthenuria",
        "urgency": "low",
        "icd10": "R82.9",
        "keywords": ["specific gravity", "hydration", "isosthenuria", "concentrated"],
    },
]


URINE_NER_EXTENSION = {
    "urine_parameters": [
        {"name": "glucose", "unit": "mg/dL", "normal": "negative", "abnormal_threshold": ">=50 mg/dL", "icd10": "R81"},
        {"name": "protein", "unit": "mg/dL", "normal": "negative/trace", "abnormal_threshold": ">=1+", "icd10": "R80"},
        {"name": "ketones", "unit": "mg/dL", "normal": "negative", "abnormal_threshold": ">=1+", "icd10": "R82.4"},
        {"name": "blood", "unit": "", "normal": "negative", "abnormal_threshold": "positive", "icd10": "R31"},
        {"name": "nitrite", "unit": "", "normal": "negative", "abnormal_threshold": "positive", "icd10": "R82.8"},
        {"name": "leukocyte_esterase", "unit": "", "normal": "negative", "abnormal_threshold": "positive", "icd10": "R82.8"},
        {"name": "bilirubin", "unit": "", "normal": "negative", "abnormal_threshold": "positive", "icd10": "R82.2"},
        {"name": "urobilinogen", "unit": "EU/dL", "normal": "0.1-1.0", "abnormal_threshold": ">1.0", "icd10": "R82.2"},
        {"name": "ph", "unit": "", "normal": "4.5-8.0", "abnormal_threshold": "<4.5 or >8.0", "icd10": "R82.9"},
        {"name": "specific_gravity", "unit": "", "normal": "1.005-1.030", "abnormal_threshold": "<1.005 or >1.030", "icd10": "R82.9"},
        {"name": "wbc", "unit": "/HPF", "normal": "0-5", "abnormal_threshold": ">5", "icd10": "R82.8"},
        {"name": "rbc", "unit": "/HPF", "normal": "0-3", "abnormal_threshold": ">3", "icd10": "R31"},
        {"name": "rbc_casts", "unit": "", "normal": "absent", "abnormal_threshold": "present", "icd10": "N05"},
        {"name": "wbc_casts", "unit": "", "normal": "absent", "abnormal_threshold": "present", "icd10": "N39.0"},
        {"name": "granular_casts", "unit": "", "normal": "absent", "abnormal_threshold": "present", "icd10": "N17"},
        {"name": "bacteria", "unit": "/HPF", "normal": "absent", "abnormal_threshold": "present", "icd10": "N39.0"},
        {"name": "albumin_creatinine_ratio", "unit": "mg/g", "normal": "<30", "abnormal_threshold": ">=30", "icd10": "R80"},
        {"name": "protein_creatinine_ratio", "unit": "mg/mmol", "normal": "<20", "abnormal_threshold": ">=30", "icd10": "R80"},
    ],
    "pattern_rules": [
        {"pattern": "UTI", "criteria": "nitrite=positive AND leukocyte_esterase=positive", "urgency": "high"},
        {"pattern": "DKA", "criteria": "glucose>=2+ AND ketones>=2+", "urgency": "critical"},
        {"pattern": "Nephrotic", "criteria": "protein>=3+", "urgency": "high"},
        {"pattern": "Nephritic", "criteria": "rbc_casts=present AND blood=positive", "urgency": "high"},
        {"pattern": "Renal_TB_suspected", "criteria": "wbc>5 AND nitrite=negative", "urgency": "high"},
        {"pattern": "Obstructive_jaundice", "criteria": "bilirubin=positive AND urobilinogen=absent", "urgency": "high"},
        {"pattern": "Hemolytic", "criteria": "urobilinogen>1 AND bilirubin=negative", "urgency": "medium"},
        {"pattern": "Pre_eclampsia", "criteria": "protein>=1+ AND pregnancy=true", "urgency": "critical"},
    ],
}


URINE_NER_PROMPT = """You are a clinical NER system specialized in urine reports.
Extract all urine analysis parameters from the text. Return ONLY valid JSON.

Schema:
{{
  "report_type": "urinalysis",
  "dipstick": {{
    "glucose": {{"value": "string", "flag": "normal|abnormal"}},
    "protein": {{"value": "string", "flag": "normal|abnormal"}},
    "ketones": {{"value": "string", "flag": "normal|abnormal"}},
    "blood": {{"value": "string", "flag": "normal|abnormal"}},
    "nitrite": {{"value": "string", "flag": "normal|abnormal"}},
    "leukocyte_esterase": {{"value": "string", "flag": "normal|abnormal"}},
    "bilirubin": {{"value": "string", "flag": "normal|abnormal"}},
    "urobilinogen": {{"value": "string", "flag": "normal|abnormal"}},
    "ph": {{"value": "string", "flag": "normal|abnormal"}},
    "specific_gravity": {{"value": "string", "flag": "normal|abnormal"}}
  }},
  "microscopy": {{
    "wbc": {{"value": "string", "unit": "/HPF", "flag": "normal|abnormal"}},
    "rbc": {{"value": "string", "unit": "/HPF", "flag": "normal|abnormal"}},
    "casts": {{"rbc_casts": "absent|present", "wbc_casts": "absent|present", "granular_casts": "absent|present"}},
    "bacteria": "absent|few|moderate|many",
    "epithelial_cells": "string"
  }},
  "quantitative": {{
    "albumin_creatinine_ratio": {{"value": number, "unit": "mg/g", "flag": "normal|abnormal"}},
    "protein_creatinine_ratio": {{"value": number, "unit": "mg/mmol", "flag": "normal|abnormal"}},
    "24hr_protein": {{"value": number, "unit": "g/day", "flag": "normal|abnormal"}}
  }},
  "detected_patterns": ["string"],
  "conditions": ["string"],
  "urgency": "routine|follow_up|urgent|emergency"
}}

Urine Report Text:
{text}
"""


if __name__ == "__main__":
    print(f"Urinalysis KB entries : {len(URINALYSIS_KNOWLEDGE_BASE)}")
    print(f"Urine NER parameters  : {len(URINE_NER_EXTENSION['urine_parameters'])}")
    print(f"Pattern rules         : {len(URINE_NER_EXTENSION['pattern_rules'])}")
