"""Add updated models with missing fields

Revision ID: 3cfb1013424a
Revises: 50c7529f111b
Create Date: 2026-04-25 15:14:44.159883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfb1013424a'
down_revision = '50c7529f111b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
