"""Add updated models with missing fields

Revision ID: 50c7529f111b
Revises: 
Create Date: 2026-04-25 15:12:43.372688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c7529f111b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    analysis_status = postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus')
    analysis_status.create(op.get_bind())
    op.add_column('claims', sa.Column('source_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('claims', sa.Column('verdict', sa.String(length=20), nullable=True))
    op.add_column('claims', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('claims', sa.Column('hallucination_detected', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('claims', sa.Column('hallucination_details', sa.JSON(), nullable=True))
    op.add_column('claims', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('claims', 'claim_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('claims', 'disclaimer',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('image_analyses', sa.Column('file_format', sa.String(length=10), nullable=True))
    op.add_column('image_analyses', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus'), nullable=False, server_default='PENDING'))
    op.add_column('image_analyses', sa.Column('dicom_metadata', sa.JSON(), nullable=True))
    op.add_column('image_analyses', sa.Column('segmentation_overlay', sa.String(length=500), nullable=True))
    op.add_column('image_analyses', sa.Column('segmentation_confidence', sa.Float(), nullable=True))
    op.add_column('image_analyses', sa.Column('gradcam_regions', sa.JSON(), nullable=True))
    op.add_column('image_analyses', sa.Column('classification_probs', sa.JSON(), nullable=True))
    op.add_column('image_analyses', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('image_analyses', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('image_analyses', sa.Column('retrieved_sources', sa.JSON(), nullable=True))
    op.add_column('image_analyses', sa.Column('anomaly_detected', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('image_analyses', sa.Column('medical_disclaimer', sa.Text(), nullable=True))
    op.add_column('image_analyses', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('patient_code', sa.String(length=50), nullable=False, server_default='legacy_patient'))
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(length=10), nullable=True))
    op.create_unique_constraint(op.f('uq_patients_patient_code'), 'patients', ['patient_code'])
    op.add_column('reports', sa.Column('file_format', sa.String(length=10), nullable=True))
    op.add_column('reports', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus'), nullable=False, server_default='PENDING'))
    op.add_column('reports', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('risk_factors', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('shap_values', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('anomalies', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('retrieved_sources', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('medical_disclaimer', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'raw_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'raw_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('reports', 'completed_at')
    op.drop_column('reports', 'medical_disclaimer')
    op.drop_column('reports', 'confidence_score')
    op.drop_column('reports', 'retrieved_sources')
    op.drop_column('reports', 'explanation')
    op.drop_column('reports', 'anomalies')
    op.drop_column('reports', 'shap_values')
    op.drop_column('reports', 'risk_factors')
    op.drop_column('reports', 'risk_score')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'file_format')
    op.drop_constraint(op.f('uq_patients_patient_code'), 'patients', type_='unique')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'age')
    op.drop_column('patients', 'patient_code')
    op.drop_column('image_analyses', 'completed_at')
    op.drop_column('image_analyses', 'medical_disclaimer')
    op.drop_column('image_analyses', 'anomaly_detected')
    op.drop_column('image_analyses', 'retrieved_sources')
    op.drop_column('image_analyses', 'confidence_score')
    op.drop_column('image_analyses', 'explanation')
    op.drop_column('image_analyses', 'classification_probs')
    op.drop_column('image_analyses', 'gradcam_regions')
    op.drop_column('image_analyses', 'segmentation_confidence')
    op.drop_column('image_analyses', 'segmentation_overlay')
    op.drop_column('image_analyses', 'dicom_metadata')
    op.drop_column('image_analyses', 'status')
    op.drop_column('image_analyses', 'file_format')
    op.alter_column('claims', 'disclaimer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('claims', 'claim_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('claims', 'completed_at')
    op.drop_column('claims', 'hallucination_details')
    op.drop_column('claims', 'hallucination_detected')
    op.drop_column('claims', 'explanation')
    op.drop_column('claims', 'verdict')
    op.drop_column('claims', 'source_count')
    # ### end Alembic commands ###
