"""add missing claim columns

Revision ID: 5c951e5afb00
Revises: 0a0a0a0a0a0a
Create Date: 2026-05-04 15:30:39.920259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c951e5afb00'
down_revision = '0a0a0a0a0a0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('retrieved_sources', sa.JSON(), nullable=True))
    op.alter_column('claims', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'VERIFIED', 'REFUTED', 'UNCERTAIN', 'FAILED', name='claimstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('image_analyses', 'image_type',
               existing_type=postgresql.ENUM('XRAY', 'CT', 'MRI', 'SKIN', 'PATHOLOGY', name='imagetype'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('image_analyses', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=postgresql.ENUM('LAB', 'CLINICAL', 'DISCHARGE', name='reporttype'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus'),
               existing_nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LAB', 'CLINICAL', 'DISCHARGE', name='reporttype'),
               nullable=False)
    op.alter_column('image_analyses', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='analysisstatus'),
               existing_nullable=False)
    op.alter_column('image_analyses', 'image_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('XRAY', 'CT', 'MRI', 'SKIN', 'PATHOLOGY', name='imagetype'),
               nullable=False)
    op.alter_column('claims', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'VERIFIED', 'REFUTED', 'UNCERTAIN', 'FAILED', name='claimstatus'),
               existing_nullable=False)
    op.drop_column('claims', 'retrieved_sources')
    # ### end Alembic commands ###
